---

- name: This playbook install and Start a package on nodes
  hosts: all
  tasks:
    - name: Install latest version of chrony
      package:
        name: chrony
        state: latest
    
    - name: Start and enable the chronyd service
      service:
        name: chronyd
        state: started
        enabled: true